name: MyProject
options:
  bundleIdPrefix: com.myapp
  
  
targets:

  MyApp:
    scheme:
      testTargets:
        - MyUnitTests
        - MyUITests
      gatherCoverageData: true
    type: application
    sources: MyApp
    settings:
      CUSTOM_BUILD_SETTING: my_value
    dependencies:
      - target: MyFramework
    removeHeaders: false 
    platform: iOS
    deploymentTarget: "9.0"

  MyFramework:
    type: framework
    sources: MyFramework
    scheme:
      testTargets:
        - MyFrameworkUnitTests
      gatherCoverageData: true
    platform: iOS
    deploymentTarget: "9.0"

  MyFrameworkUnitTests:
    type: bundle.unit-test
    sources: MyFrameworkUnitTests
    platform: iOS
    deploymentTarget: "9.0"


  MyUnitTests:
    type: bundle.unit-test
    
    sources: MyUnitTests
    platform: iOS
    deploymentTarget: "9.0"

  MyUITests:
    type: bundle.ui-testing
    sources: MyUITests
    dependencies: 
      - target: MyApp
    platform: iOS
    deploymentTarget: "9.0"

    
    